#!/usr/bin/env bash

cmake -S . -B build -G Ninja \
    -DGLFW_ROOT="$CXXLIBS/glfw" \
    -DGLM_ROOT="$CXXLIBS/glm" \
    -DSTB_ROOT="$CXXLIBS/stb"

cmake --build build

if [ $? -ne 0 ]; then
    exit 1
fi

cd build && ctest -V --output-on-failure

